<Project>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <WarningsAsErrors>nullable</WarningsAsErrors>
        <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
        <Deterministic>true</Deterministic>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup Label="Package metadata" Condition="$(MSBuildProjectDirectory.Contains('/src/')) Or $(MSBuildProjectDirectory.Contains('\src\'))">
        <IsPackable>true</IsPackable>
        <Authors>Ayman Elfaki</Authors>
        <Company>Huia</Company>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Ayman-Elfaki/Huia</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Ayman-Elfaki/Huia</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>huia-icon.png</PackageIcon>
        <PackageTags>identity;openiddict;oauth;oidc;aspnetcore;efcore</PackageTags>
        <Version>1.0.0</Version>
    </PropertyGroup>

    <ItemGroup Label="Readme" Condition="$(MSBuildProjectDirectory.Contains('/src/')) Or $(MSBuildProjectDirectory.Contains('\src\'))">
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)assets/huia-icon.png" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <PropertyGroup Label="Test/sample projects" Condition="!$(MSBuildProjectDirectory.Contains('/src/')) And !$(MSBuildProjectDirectory.Contains('\src\'))">
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);CA1707;MA0004</NoWarn>
    </PropertyGroup>

    <ItemGroup Label="Analyzers" Condition="$(MSBuildProjectDirectory.Contains('/src/')) Or $(MSBuildProjectDirectory.Contains('\src\'))">
        <PackageReference Include="Meziantou.Analyzer" PrivateAssets="all"/>
    </ItemGroup>

</Project>
