<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Shop.Api</RootNamespace>
    <UserSecretsId>huia-shop-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\dotnet\src\Huia\Huia.csproj" />
    <ProjectReference Include="..\..\src\dotnet\src\Huia.Headless\Huia.Headless.csproj" />
    <ProjectReference Include="..\..\src\dotnet\src\Huia.Headless.EntityFrameworkCore\Huia.Headless.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
