<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Huia.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Huia.AspNetCore\Huia.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\..\samples\Huia.IdentityServer\Huia.IdentityServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

</Project>
