<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Huia.Cli</RootNamespace>
    <UserSecretsId>huia-cli</UserSecretsId>
    <AssemblyName>huia</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
