<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit"/>
        <PackageReference Include="Scalar.AspNetCore"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all"/>
        <PackageReference Include="MR.AspNetCore.Pagination"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Huia.EntityFrameworkCore\Huia.EntityFrameworkCore.csproj"/>
        <ProjectReference Include="..\Huia.ServiceDefaults\Huia.ServiceDefaults.csproj"/>
    </ItemGroup>


</Project>
